# .github/workflows/main.yml
name: HTML, CSS, JS Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install linters
        run: |
          npm install -g htmlhint stylelint eslint

      # run: htmlhint src/index.html

      - name: Lint CSS
        run: stylelint "**/*.css"

      - name: Lint JS
        run: eslint js/*.js
